### PR TITLE
ADT 3.3.5 support

### PR DESCRIPTION
**Pull request by Grymskvll**
I mostly completed support for ADT 3.3.5
I'm not a great programmer so take this with a heap of salt. Hopefully it can be at least a little useful.

It's fairly straight forward except for how offset values are handled:
There's a whole bunch of offset values throughout ADTs and they need to be updated if there's a change in size somewhere. For this purpose I added an OFFSET class. All OFFSET instances need to get updated via the ADTFile._size_changed function whenever a change occurs.
In hindsight this might not be the best solution. I kind of like the idea of being able to create a valid ADT from scratch, which isn't currently possible because the offsets need to be valid from the start (when they're read from the file). But for now it works.

I formatted ADT flags as binary because I think it makes more sense, but it's easy to change to hex if you prefer.

I added some functions to safely handle more complex operations. Most of them are in the ADTFile class, and a couple in the MCNK class:

```
ADTFile
	add_texture_filename(filename, mtxf_flags=0)
	replace_texture_filename(index, new_filename)
	remove_texture_filename(index)

	add_m2_filename(filename)
	replace_m2_filename(index, new_filename)
	remove_m2_filename(index)

	add_wmo_filename(filename)
	replace_wmo_filename(index, new_filename)
	remove_wmo_filename(index)

	add_m2_instance(which_chunks, name_id, unique_id, position, rotation, scale, flags)
	remove_m2_instance(index)

	add_wmo_instance(which_chunks, name_id, unique_id, position, rotation, extents, flags, doodad_set, name_set, scale)
	remove_wmo_instance(index)


MCNK
	add_sound_emitter(entry_id, position, size)
	remove_sound_emitter(index)

	add_texture_layer(texture_id, flags, effect_id)
	remove_texture_layer(index)
```

### CODE REVIEW

**Comment by Grymskvll** [comment]
PS sorry for the nonsensical first commit message. I didn't think it would show up in the master branch.

**Comment by skarnproject** [comment]
Did you test if it works on any example files?

**Comment by Grymskvll** [comment]
While double-checking, I found a bug that happens when adding (probably also when removing) texture alpha layers. Sorry for submitting buggy code. Everything else seems to work fine, and I'll try to fix the bug(s).

Here's what I tested:
Notes: 
- azeroth_37_35_cute.adt is an unmodified version
- chunk [2][0] of this adt only has 3 texture layers, so a fourth one (with alpha) is added for testing
- I also did some tests in northrend_25_19.adt to make sure highres alpha read/write works
- didn't thoroughly test sound emitters yet

```
# add new tex definition, replace texture_id of a layer
# VERIFIED working IN-GAME
quit()
python
from pywowlib.adt_file import *
adt = ADTFile("E:/Games/3.3.5 - WoW/project01/world/maps/azeroth/azeroth_37_35_cute.adt", False)
t_id = adt.add_texture_filename("tileset\\ashzara\\ashzarabeachgrassgreen.blp")
adt.mcnk[0][0].mcly.layers[3].texture_id = t_id
adt.write("E:/Games/3.3.5 - WoW/project01/world/maps/azeroth/azeroth_37_35.adt", False)


# replace texture_id of a layer
# VERIFIED working IN-GAME
quit()
python
from pywowlib.adt_file import *
adt = ADTFile("E:/Games/3.3.5 - WoW/project01/world/maps/azeroth/azeroth_37_35_cute.adt", False)
adt.mcnk[0][0].mcly.layers[3].texture_id = 5
adt.write("E:/Games/3.3.5 - WoW/project01/world/maps/azeroth/azeroth_37_35.adt", False)


# add new m2 definition, add instance to adt
# VERIFIED working IN-GAME
quit()
python
from pywowlib.adt_file import *
adt = ADTFile("E:/Games/3.3.5 - WoW/project01/world/maps/azeroth/azeroth_37_35_cute.adt", False)
name_id = adt.add_m2_filename("world\\expansion02\\doodads\\generic\\scourge\\sc_cauldron_green.m2")
which_chunks	= [(0,0)]
# name_id			= 10
unique_id		= 123123123
position		= (19760.9, 39.171, 18714.2)
rotation		= (0, 0, 0)
scale			= 307
flags			= 0
adt.add_m2_instance(which_chunks, name_id, unique_id, position, rotation, scale, flags)
adt.write("E:/Games/3.3.5 - WoW/project01/world/maps/azeroth/azeroth_37_35.adt", False)


# add new m2 definition, add instance to adt, replace m2 filename
# VERIFIED working IN-GAME
quit()
python
from pywowlib.adt_file import *
adt = ADTFile("E:/Games/3.3.5 - WoW/project01/world/maps/azeroth/azeroth_37_35_cute.adt", False)
name_id = adt.add_m2_filename("world\\expansion02\\doodads\\generic\\scourge\\sc_cauldron_green.m2")
which_chunks	= [(0,0)]
# name_id			= 10
unique_id		= 123123123
position		= (19760.9, 39.171, 18714.2)
rotation		= (0, 0, 0)
scale			= 307
flags			= 0
adt.add_m2_instance(which_chunks, name_id, unique_id, position, rotation, scale, flags)
adt.replace_m2_filename(name_id, "world\\expansion02\\doodads\\dragonblight\\db_dragonhead01.m2")
adt.write("E:/Games/3.3.5 - WoW/project01/world/maps/azeroth/azeroth_37_35.adt", False)


# add new m2 definition, add instance to adt, remove instance, remove def
# VERIFIED identical file
quit()
python
from pywowlib.adt_file import *
adt = ADTFile("E:/Games/3.3.5 - WoW/project01/world/maps/azeroth/azeroth_37_35_cute.adt", False)
name_id = adt.add_m2_filename("world\\expansion02\\doodads\\generic\\scourge\\sc_cauldron_green.m2")
which_chunks	= [(0,0)]
# name_id			= 10
unique_id		= 123123123
position		= (19760.9, 39.171, 18714.2)
rotation		= (0, 0, 0)
scale			= 307
flags			= 0
adt.add_m2_instance(which_chunks, name_id, unique_id, position, rotation, scale, flags)
adt.remove_m2_instance(595)
adt.remove_m2_filename(name_id)
adt.write("E:/Games/3.3.5 - WoW/project01/world/maps/azeroth/azeroth_37_35.adt", False)


# add new wmo definition, add instance to adt
# VERIFIED working IN-GAME
quit()
python
from pywowlib.adt_file import *
adt = ADTFile("E:/Games/3.3.5 - WoW/project01/world/maps/azeroth/azeroth_37_35_cute.adt", False)
name_id = adt.add_wmo_filename("world\\wmo\\dungeon\\micro_dungeons\\nd_bearcave_icecrown.wmo")

which_chunks	= [(0,0)]
# name_id			= 2
unique_id		= 456456456
position		= (19847.6, 61.9206, 18929.2)
rotation		= (0, 0, 0)
extents			= ((20260.99, 48.65194, 18983.21), (20521.02, 87.42275, 19251.26))
flags			= 0
doodad_set		= 0
name_set		= 0
scale			= 0
adt.add_wmo_instance(which_chunks, name_id, unique_id, position, rotation, extents, flags, doodad_set, name_set, scale)
adt.write("E:/Games/3.3.5 - WoW/project01/world/maps/azeroth/azeroth_37_35.adt", False)


# add new wmo definition, add instance to adt, replace wmo filename
# VERIFIED working IN-GAME
quit()
python
from pywowlib.adt_file import *
adt = ADTFile("E:/Games/3.3.5 - WoW/project01/world/maps/azeroth/azeroth_37_35_cute.adt", False)
name_id = adt.add_wmo_filename("world\\wmo\\dungeon\\micro_dungeons\\nd_bearcave_icecrown.wmo")
which_chunks	= [(0,0)]
# name_id			= 2
unique_id		= 456456456
position		= (19847.6, 61.9206, 18929.2)
rotation		= (0, 0, 0)
extents			= ((20260.99, 48.65194, 18983.21), (20521.02, 87.42275, 19251.26))
flags			= 0
doodad_set		= 0
name_set		= 0
scale			= 0
adt.add_wmo_instance(which_chunks, name_id, unique_id, position, rotation, extents, flags, doodad_set, name_set, scale)
adt.replace_wmo_filename(4, "world\\wmo\\northrend\\icecrown\\scourgewalls\\icecrown_tower_reg_01.wmo")
adt.write("E:/Games/3.3.5 - WoW/project01/world/maps/azeroth/azeroth_37_35.adt", False)


# add new wmo definition, add instance to adt, remove instance, remove filename
# VERIFIED identical file
quit()
python
from pywowlib.adt_file import *
adt = ADTFile("E:/Games/3.3.5 - WoW/project01/world/maps/azeroth/azeroth_37_35_cute.adt", False)
name_id = adt.add_wmo_filename("world\\wmo\\dungeon\\micro_dungeons\\nd_bearcave_icecrown.wmo")

which_chunks	= [(0,0)]
# name_id			= 2
unique_id		= 456456456
position		= (19847.6, 61.9206, 18929.2)
rotation		= (0, 0, 0)
extents			= ((20260.99, 48.65194, 18983.21), (20521.02, 87.42275, 19251.26))
flags			= 0
doodad_set		= 0
name_set		= 0
scale			= 0
adt.add_wmo_instance(which_chunks, name_id, unique_id, position, rotation, extents, flags, doodad_set, name_set, scale)
adt.remove_wmo_instance(6)
adt.remove_wmo_filename(name_id)
adt.write("E:/Games/3.3.5 - WoW/project01/world/maps/azeroth/azeroth_37_35.adt", False)


# add texture layer, remove after
# VERIFIED identical file
quit()
python
from pywowlib.adt_file import *
adt = ADTFile("E:/Games/3.3.5 - WoW/project01/world/maps/azeroth/azeroth_37_35_cute.adt", False)
adt.mcnk[2][0].add_texture_layer(0, 256, 0)
adt.mcnk[2][0].mcal.layers[2].alpha_map = [[200 for _ in range(64)] for _ in range(64)]
adt.mcnk[2][0].remove_texture_layer(3)
adt.write("E:/Games/3.3.5 - WoW/project01/world/maps/azeroth/azeroth_37_35.adt", False)


# add texture layer
# BUGGED (MCSE offset isn't updated)
quit()
python
from pywowlib.adt_file import *
adt = ADTFile("E:/Games/3.3.5 - WoW/project01/world/maps/azeroth/azeroth_37_35_cute.adt", False)
adt.mcnk[2][0].add_texture_layer(0, 256, 0)
adt.mcnk[2][0].mcal.layers[2].alpha_map = [[255 for _ in range(64)] for _ in range(64)]
adt.write("E:/Games/3.3.5 - WoW/project01/world/maps/azeroth/azeroth_37_35.adt", False)

```

**Comment by skarnproject** [comment]
If you are interested on working on pywowlib more and have Discord, feel free to add me as Skarn#6841, so I can give you push access and we avoid pull requests which slow things down.

**Pull request merged**
